/* Filter Action Types */
export const UPDATE_FILTER_TYPE = "UPDATE_FILTER_TYPE";
export const UPDATE_FILTER_CAPACITY = "UPDATE_FILTER_CAPACITY";
export const UPDATE_FILTER_PRICE = "UPDATE_FILTER_PRICE";
export const UPDATE_FILTER_MIN_PRICE = "UPDATE_FILTER_MIN_PRICE";
export const UPDATE_FILTER_MAX_PRICE = "UPDATE_FILTER_MAX_PRICE";
export const UPDATE_FILTER_MIN_SIZE = "UPDATE_FILTER_MIN_SIZE";
export const UPDATE_FILTER_MAX_SIZE = "UPDATE_FILTER_MAX_SIZE";
export const UPDATE_FILTER_BREAKFAST = "UPDATE_FILTER_BREAKFAST";
export const UPDATE_FILTER_PETS = "UPDATE_FILTER_PETS";

/* Room Action Types */
export const UPDATE_SORTED_ROOMS = "UPDATE_SORTED_ROOMS";
